AddressBookMarch/Controllers/AddressBookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.SqlServer.Server;
using System.Dynamic;
using System.Web.Mvc;
using Model.Models;
using Domain.Services;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace UserInterface.Controllers
{
    public class AddressBookController : Controller
    {
        private IServices actions;

        public AddressBookController(IServices actions)
        {
            this.actions = actions;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View(new ContactInformation());
        }
        public IActionResult Insert(ContactInformation contact)
        {
            if (ModelState.IsValid)
            {
                actions.InsertContact(contact);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Form");
        }
        public IActionResult ViewDetails(int Id)
        {
            if(ModelState.IsValid) 
            {
                return View(actions.GetContactById(Id));
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(ContactInformation contact)
        {
            actions.DeleteContact(contact);
            return RedirectToAction("Index");
        }
        public IActionResult EditForm(int Id)
        {
            var contact = actions.GetContactById(Id);
            if(contact == null)
            {
                return RedirectToAction("Index");
            }
            return View(contact);
        }
        public IActionResult UpdateContact(ContactInformation contact)
        {
            actions.UpdateContact(contact);
            return RedirectToAction("Index");
        }
    }
}

AddressBookMarch/ViewComponents/ContactsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repository.RepositoryFiles;

namespace UserInterface.ViewComponents
{
    public class ContactsViewComponent : ViewComponent
    {
        private IAddressBookActions actions;
        public ContactsViewComponent(IAddressBookActions actions)
        {
            this.actions = actions;
        }
        public IViewComponentResult Invoke()
        {
            return View(actions.GetContactList());   
        }
    }
}

AddressBookMarch/Views/AddressBook/EditForm.cshtml
@model Model.Models.ContactInformation

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<html>
    <head>
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </head>
    <body>
    <form id="form" asp-action="UpdateContact" asp-route-id="@Model.Id">
            <div class="form-items">
            <label for="name">Name</label><span asp-validation-for="Name" class="text-danger"></span><br />
            <input type="text" id="name" asp-for="Name" /><br />
            <label for="email">Email</label><span asp-validation-for="Email" class="text-danger"></span><br />
            <input type="text" id="email" asp-for="Email" /><br />
                <div class="contact-labels">
                <label for="mobile">Mobile</label><span asp-validation-for="Mobile" class="text-danger"></span>
                    <label for="landline">Landline</label>
                </div>
                <div class="contact-inputs">
                <input type="text" id="mobile" asp-for="Mobile" />
                <input type="text" id="landline" asp-for="Landline"  />
                </div>
            <label for="website">Website</label><span asp-validation-for="Website" class="text-danger"></span><br />
            <input type="text" id="website" asp-for="Website" /><br />
            <label for="address">Address</label><br />
            <textarea id="address" asp-for="Address" rows="8"></textarea><br />
                <button type="submit" class="add-details" >Update</button>
            </div>
        </form>
    </body>
</html>

AddressBookMarch/Views/AddressBook/Form.cshtml
@model Model.Models.ContactInformation
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
    <form id="form" asp-controller="AddressBook" asp-action="Insert" method="post">
        <div class="form-items">
            <label for="name">Name</label><span asp-validation-for="Name" class="text-danger"></span><br />
            <input type="text" id="name" asp-for="Name" /><br />

            <label for="email">Email</label><span asp-validation-for="Email" class="text-danger"></span><br />
            <input type="text" id="email" asp-for="Email" /><br />


            <div class="contact-labels">
                <label for="mobile">Mobile</label>
                <span asp-validation-for="Mobile" class="text-danger"></span>
                <label for="landline">Landline</label>
                <span asp-validation-for="Landline" class="text-danger"></span>
            </div>
            <div class="contact-inputs">
                <input type="text" id="mobile" asp-for="Mobile" />
                <input type="text" id="landline" asp-for="Landline" />
            </div>
            <label for="website">Website</label><span asp-validation-for="Website" class="text-danger"></span><br />
            <input type="text" id="website" asp-for="Website" /><br />

            <label for="address">Address</label><br />

            <textarea id="address" asp-for="Address" rows="8"></textarea><br />
            <button type="submit" class="add-details">Add</button>
        </div>
    </form>
</body>
</html>

AddressBookMarch/Views/AddressBook/Index.cshtml
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />

AddressBookMarch/Views/AddressBook/ViewDetails.cshtml
@model Model.Models.ContactInformation
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
    <div class="right-body" id="full-details">
        <div class="edit-delete">
            <img src="~/images/edit1.jpg" alt="edit" class="edit-icon"> <a class="edit-text" asp-action="EditForm" asp-route-Id="@Model.Id">Edit</a>
            <img src="~/images/delete1.png" alt="delete" class="delete-icon"> <a class="delete-text" asp-action="Delete" asp-route-Id="@Model.Id">Delete</a>
        </div>
        <div class="full-details">
            <p id='right-name'>@Model.Name</p>
            <div class="email-set"> <p id='email-label'>Email Id :</p><p id='right-email'>@Model.Email</p></div>
            <div class='mobile-set'><p id='mobile-number-label'>Mobile Number :</p><p id='right-mobile'>@Model.Mobile</p></div>
            <div class='landline-set'><p id='landline-label'>Landline : </p><p id='right-landline'>@Model.Landline</p></div>
            <div class='website-set'><p id='website-label'>Website :</p><p id='right-website'>@Model.Website</p></div>
            <div class='address-set'><p id='address-label'>Address :</p><p id='right-address'>@Model.Address</p></div>
        </div>
    </div>
</body>
</html>

AddressBookMarch/Views/Home/AddForm.cshtml
<form class="add-contact-form" id="form">
    <div class="form-items">
        <label for="name">Name</label><span id="name-field-check" class="validations">*</span><br />
        <input type="text" id="name" name="name" /><br />
        <label for="email">Email</label><span id="email-field-check" class="validations">*</span><br />
        <input type="text" id="email" name="email" onkeyup="validateEmailId()" /><br />
        <div class="contact-labels">
            <label for="mobile">Mobile</label><span id="mobile-field-check" class="validations">*</span>
            <label for="landline">Landline</label><span id="landline-check" class="validations"></span>
        </div>
        <div class="contact-inputs">
            <input type="text" id="mobile" name="mobile" onblur="validateMobileNumber()" />
            <input type="text" id="landline" name="landline" onblur="validateLandline()" />
        </div>
        <label for="website">Website</label><span id="website-check" class="validations">*</span> <br />
        <input type="text" id="website" name="website" onkeyup="validateWebsite()" /><br />
        <label for="address">Address</label><br />
        <textarea id="address" name="address" rows="8"></textarea><br />
        <button id="add-button" class="add-details" onclick="groupFormData(this.id)">Add</button>
    </div>
</form>

AddressBookMarch/Views/Home/Form.cshtml
@model Model.Models.ContactInformation


<html>
    <head>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    </head>
    <body>
        <div class="page-header">
        <h1 class="page-heading">Address Book</h1>
    </div>
    <div class="page-navigators">
        <ul class="navigator-items">
            <li class="navigator-item">Home</li>
            <li class="navigator-item">
                <a asp-area="" asp-controller="AddressBook" asp-action="Form">+Add</a>
            </li>
            <img class="nav-blog-image" src="blog-icon.png" alt="blog image" />
        </ul>
    </div>
        <div class="main-body">
        <p class="contact">Contact</p>
        <form class="add-contact-form" id="form">
            <div class="form-items">
                <label for="name">Name</label><br />
                <input type="text" id="name" name="name" /><br />
                <label for="email">Email</label><br />
                <input type="text" id="email" asp-for="Email" onkeyup="validateEmailId()" /><br />
                <div class="contact-labels">
                    <label for="mobile">Mobile</label><span id="mobile-field-check" class="validations">*</span>
                    <label for="landline" id="land-line">Landline</label><span id="landline-check" class="validations"></span>
                </div>
                <div class="contact-inputs">
                    <input type="text" id="mobile" asp-for="Mobile" onblur="validateMobileNumber()" />
                    <input type="text" id="landline" asp-for="Landline" onblur="validateLandline()" />
                </div>
                <label for="website">Website</label><span id="website-check" class="validations">*</span> <br />
                <input type="text" id="website" asp-for="Website" onkeyup="validateWebsite()" /><br />
                <label for="address">Address</label><br />
                <textarea id="address" asp-for="Address"></textarea><br />
                <button id="add-button" class="add-details" onclick="groupFormData(this.id)">Add</button>
            </div>
        </form>
    </body>
</html>

AddressBookMarch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AddressBookMarch/Views/Shared/Components/Contacts/Default.cshtml
@model IEnumerable<Model.Models.ContactInformation>
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    @foreach (var item in Model)
    {
            <div class="border  left-details">
                <a class="short-details" asp-controller="AddressBook" asp-action="ViewDetails" asp-route-Id="@item.Id">
                    <p class="fs-2">@item.Name</p>
                    <p class="fs-6">@item.Email</p>
                    <p class="fs-6">@item.Mobile</p>
                </a>
            </div>
    }
</body>
</html>

AddressBookMarch/Views/Shared/Details.cshtml
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    @foreach (var item in @ViewBag.TotalContacts)
{
   <div class="border w-25 left-details" >
            <a class="short-details" asp-controller="AddressBook" asp-action="ViewDetails" asp-route-Id="@item.Id">
        <p class="fs-5">@item.Name</p>
        <p class="fs-6">@item.Email</p>
        <p class="fs-6">@item.Mobile</p>
        </a>
    </div> 
}
    </body>
</html>

AddressBookMarch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBookasp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href ="~/css/style.css" asp-append-version="true"/>
</head>
<body>
    
    <div class="page-header">
        <h1 class="page-heading">Address Book</h1>
    </div>
    <div class="page-navigators">
        <ul class="navigator-items">
            <li class="navigator-item"><a asp-area="" asp-controller="AddressBook" asp-action="Index">Home</a></li>
            <li class="navigator-item">
                <a asp-area="" asp-controller="AddressBook" asp-action="Form">+Add</a>
            </li>
            <img class="nav-blog-image" src="~/images/blog-icon.png" alt="blog image" />
        </ul>
    </div>
    <div class="contact-heading">Contacts</div>
    <div class="main-body">
        <div>
            @await Component.InvokeAsync("Contacts");
        </div>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
   </div >
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>